In [2]:
import re 

import pandas as pd
import plotly.express as px
from plotly import graph_objects as go

from watch import get_leaders

In [3]:
leaders_df = pd.DataFrame(get_leaders('/home/amos/.local/share/aspyr-media/Sid Meier\'s Civilization VI/Logs/GameCore.log'))
leaders_df = leaders_df[leaders_df['civilization_type'] == 'FULL_CIV']
leaders_df['civilization'] = leaders_df['civilization'].map(lambda x: f'CIVILIZATION_{x.strip()}')
leaders_df

,player_num,civilization,leader,civilization_type,player_type
0,0,CIVILIZATION_OTTOMAN,SULEIMAN,FULL_CIV,Human
1,1,CIVILIZATION_PHOENICIA,DIDO,FULL_CIV,AI
2,2,CIVILIZATION_CREE,POUNDMAKER,FULL_CIV,AI
3,3,CIVILIZATION_SUMERIA,GILGAMESH,FULL_CIV,AI
4,4,CIVILIZATION_CANADA,LAURIER,FULL_CIV,AI
5,5,CIVILIZATION_NORWAY,HARDRADA,FULL_CIV,AI
6,6,CIVILIZATION_JAPAN,HOJO,FULL_CIV,AI
7,7,CIVILIZATION_AZTEC,MONTEZUMA,FULL_CIV,AI
8,8,CIVILIZATION_FRANCE,CATHERINE DE MEDICI,FULL_CIV,AI
9,9,CIVILIZATION_KOREA,SEONDEOK,FULL_CIV,AI

In [4]:
df = pd.read_csv('/home/amos/.local/share/aspyr-media/Sid Meier\'s Civilization VI/Logs/AI_Espionage.csv', header=None, skiprows=1)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,2,2,LOC_CITY_NAME_MIKISIW_WACIHK,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
1,2,3,LOC_CITY_NAME_URUK,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
2,2,4,LOC_CITY_NAME_OTTAWA,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
3,2,5,LOC_CITY_NAME_NIDAROS,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
4,2,6,LOC_CITY_NAME_KYOTO,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,25,9,LOC_CITY_NAME_GYEONGJU,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
713,25,9,LOC_CITY_NAME_GANGNEUNG,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
714,25,9,LOC_CITY_NAME_CHUNCHEON,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
715,25,9,LOC_CITY_NAME_PASKWAW_ASKIHK,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
716,25,9,LOC_CITY_NAME_MIKISIW_WACIHK,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

In [5]:
columns = ['turn', 
           'player_id', 
           'city', 
           'UNITOPERATION_SPY_LISTENING_POST',
           'UNITOPERATION_SPY_GAIN_SOURCES',
           'UNITOPERATION_SPY_STEAL_TECH_BOOST',
           'UNITOPERATION_SPY_GREAT_WORK_HEIST',
           'UNITOPERATION_SPY_SABOTAGE_PRODUCTION',
           'UNITOPERATION_SPY_SIPHON_FUNDS',
           'UNITOPERATION_SPY_REC',
           None,
           None,
           None,
           None
           ]
df.columns = columns

In [6]:
df

,turn,player_id,city,UNITOPERATION_SPY_LISTENING_POST,UNITOPERATION_SPY_GAIN_SOURCES,UNITOPERATION_SPY_STEAL_TECH_BOOST,UNITOPERATION_SPY_GREAT_WORK_HEIST,UNITOPERATION_SPY_SABOTAGE_PRODUCTION,UNITOPERATION_SPY_SIPHON_FUNDS,UNITOPERATION_SPY_REC,None,None,None,None
0,2,2,LOC_CITY_NAME_MIKISIW_WACIHK,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
1,2,3,LOC_CITY_NAME_URUK,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
2,2,4,LOC_CITY_NAME_OTTAWA,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
3,2,5,LOC_CITY_NAME_NIDAROS,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
4,2,6,LOC_CITY_NAME_KYOTO,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,25,9,LOC_CITY_NAME_GYEONGJU,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
713,25,9,LOC_CITY_NAME_GANGNEUNG,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
714,25,9,LOC_CITY_NAME_CHUNCHEON,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
715,25,9,LOC_CITY_NAME_PASKWAW_ASKIHK,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
716,25,9,LOC_CITY_NAME_MIKISIW_WACIHK,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

In [7]:
df.columns.str.lower()

Index([                                 'turn',
                                   'player_id',
                                        'city',
            'unitoperation_spy_listening_post',
              'unitoperation_spy_gain_sources',
          'unitoperation_spy_steal_tech_boost',
          'unitoperation_spy_great_work_heist',
       'unitoperation_spy_sabotage_production',
              'unitoperation_spy_siphon_funds',
                       'unitoperation_spy_rec',
                                          None,
                                          None,
                                          None,
                                          None],
      dtype='object')